/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card.vue')['default']
    InfoCard: typeof import('./src/components/infoCard.vue')['default']
    Label: typeof import('./src/components/label.vue')['default']
    Slabel: typeof import('./src/components/slabel.vue')['default']
  }
}
